- name: json_log
  format: "$json_content"
  source_files:
    - ./test/demo.log
  relabel_config:
    source_labels:
      - componentName
      - interfaceName
      - returnCode
      - event
  histogram_buckets: [0.1, 0.3, 0.5, 1, 2]
