- name: json_log
  format: "$json_content"
  source_files:
    - ./test/req_20211230-15.log
  relabel_config:
    source_labels:
      - componentName
      - interfaceName
      - costTime
  histogram_buckets: [0.1, 0.3, 0.5, 1, 2]
